// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nujneglyxlqjhvzcmiex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51am5lZ2x5eGxxamh2emNtaWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzUyNTMsImV4cCI6MjA2MzE1MTI1M30.OipZr10a1rtqdBJYWTuK5RVPU29MKE00pheBq6I0RN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);